DisplayOnSamePageTesting/Models/DisplayContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Web;

namespace DisplayOnSamePageTesting.Models
{
    public class DisplayContext : DbContext
    {

        public DisplayContext() : base("DisplayContext")
        {
        }

        public DbSet<ItemWithProperties> Items { get; set; }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    }
}

DisplayOnSamePageTesting/Models/ItemWithProperties.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DisplayOnSamePageTesting.Models
{
    public class ItemWithProperties
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EditableProperty { get; set; }
        public string ConstantProperty { get; set; }
    }
}

DisplayOnSamePageTesting/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DisplayOnSamePageTesting.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DisplayOnSamePageTesting/Controllers/ItemWithPropertiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DisplayOnSamePageTesting.Models;
using Newtonsoft.Json;

namespace DisplayOnSamePageTesting.Controllers
{
    public class ItemWithPropertiesController : Controller
    {
        private DisplayContext db = new DisplayContext();

        // GET: ItemWithProperties
        public ActionResult Index(int? itemID)
        {
            PopulateOrganizationsDropDownList();
            if (itemID == null)
                return View();
            else
                return View(db.Items.SingleOrDefault(i => i.Id == itemID.Value));
        }

        public ActionResult AJAXIndex()
        {
            PopulateOrganizationsDropDownList();
            return View();
        }

        private void PopulateOrganizationsDropDownList(int? selectedItem = 1)
        {
            var itemQuery = from r in db.Items
                                     orderby r.Name
                                     select r;
            ViewBag.ItemId = new SelectList(itemQuery, "Id", "Name", selectedItem);
        }

        public JsonResult GetItem(int id)
        {
            var item = db.Items.SingleOrDefault(i => i.Id == id);
            //string json = JsonConvert.SerializeObject(item);
            JsonResult json = new JsonResult
            {
                Data = item,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
            return json;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DisplayOnSamePageTesting/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DisplayOnSamePageTesting/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DisplayOnSamePageTesting/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DisplayOnSamePageTesting/Views/ItemWithProperties/AJAXIndex.cshtml
@model DisplayOnSamePageTesting.Models.ItemWithProperties

@{
    ViewBag.Title = "Index";
}

<h2>AJAX Index</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Id, "Item", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ItemId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Show" class="btn btn-default" id="show" />
            </div>
        </div>

        <div id="item" hidden>
            <hr />
            <h2>Display after selecting the item</h2>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")

        <script type="text/javascript">

            function getItem(result) {
                $('#item').show()
                $('.item').remove()
                $('#item').append(

                    "<div class='item'><label>Editable Property&nbsp &nbsp</label><input type='text' /><br/><label>Constant Property&nbsp</label><input type='text' value='" + result.ConstantProperty + "' disabled /></div>"
                )
            }

            function showClicked(args) {
                var itemId = $('#ItemId').val()
                $.get("/ItemWithProperties/GetItem/" + itemId, getItem);
            }

            $().ready(function () {
                $("#show").click(showClicked);
            });

        </script>
    }
}

DisplayOnSamePageTesting/Views/ItemWithProperties/Index.cshtml
@model DisplayOnSamePageTesting.Models.ItemWithProperties

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Id, "Item", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ItemId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Show" class="btn btn-default" />
            </div>
        </div>

        @if (Model != null)
        {
            <hr />
            <h2>Display after selecting the item</h2>
            <div class="form-group">
                @Html.LabelFor(model => model.EditableProperty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EditableProperty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EditableProperty, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConstantProperty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConstantProperty, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                </div>
            </div>
        }
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DisplayOnSamePageTesting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Item Testing", "Index", "ItemWithProperties")</li>
                    <li>@Html.ActionLink("AJAX Testing", "AJAXIndex", "ItemWithProperties")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>